security enhancement: never export BW_SESSION env var externally

diff --git a/bwfzf b/bwfzf
--- a/bwfzf
+++ b/bwfzf
@@ -1,154 +1,204 @@
 #!/usr/bin/env bash
 
 bwfzf-argparse() {
-  local arg
-  local args=("$@")
-  local argIdx=0
-  while true; do
-    arg="${args[argIdx]-}"
-    (( argIdx++ )) || true
-    case "${arg}" in
-      "-v") argVerbose=true ;;
-      "-d") argDebug=true ;;
-      "-vd") argVerbose=true && argDebug=true ;;
-      "-dv") argVerbose=true && argDebug=true ;;
-      "--verbose") argVerbose=true ;;
-      "--debug") argDebug=true ;;
-      "") break ;;
-    esac
-  done
+	local arg
+	local args=( "$@" )
+	local argIdx=0
+
+	# parse any options
+	while true; do
+		arg="${args[argIdx]-}"
+		(( argIdx++ )) || true
+
+		case "${arg}" in
+			"action:get") argAction="get" ; continue ;;
+			"action:put") argAction="put" ; continue ;;
+			"-v") argVerbose=true ; continue ;;
+			"-d") argDebug=true ; continue ;;
+			"-vd") argVerbose=true && argDebug=true ; continue ;;
+			"-dv") argVerbose=true && argDebug=true ; continue ;;
+			"--verbose") argVerbose=true ; continue ;;
+			"--debug") argDebug=true ; continue ;;
+			"") break ;;
+		esac
+
+		echo "Error: Invalid invocation: '${arg}' is not a valid argument" >&2
+		exit 1
+	done
 }
 
+# Security measures:
+# - set BW_SESSION env var in subshells only; no exposure outside of subshells
+# - Here Documents (<<-EOF) used instead of echoing data over stdin throughout
+#   (avoids leaking passwords to pipe or process snooping)
+# - <<-EOF syntax favored over <<< for portability,
+#   per https://stackoverflow.com/a/21171367/11776945
+
 bwfzf() {
-  # parse args
-  local argVerbose=false
-  local argDebug=false
-  bwfzf-argparse "$@"
+	# parse optional args
+	local argVerbose=false
+	local argDebug=false
+	bwfzf-argparse "$@"
 
-  local bwItem
-  local bwItemId
-  local bwItems
-  local keyPressed
-  local lastAction
-  local nextField
-  local sessionKey
+	if [[ "${argVerbose}" == false ]]; then
+		clear
+	fi
 
-  if [[ "${argVerbose}" == false ]]; then
-    clear
-  fi
+	local sessionKey
 
-  # use "Here Documents" piping to send "bw list items" result (which contains passwords)
-  # securly to jq which will sanitize it into a list of "name username id" rows (no passwords)
-  # this avoids leaking sensitive variable contents to pipe or process snooping
-  # <<EOF used instead of <<< for portability, per https://stackoverflow.com/a/21171367/11776945
-  bwItems="$(jq -r '.[] | "\(.name) · \(.login.username) \(.id)"' 2> /dev/null <<EOF
-    $(bw list items)
-EOF
-  )"
+	# if no session key was passed, attempt to retrieve it from persistence
+	if [[ -z "${sessionKey}" ]]; then
+		if hash bwfzf-session-persistence 2>/dev/null; then
+			sessionKey=$( bwfzf-session-persistence action:get "$@" )
+		fi
+	fi
 
-  # if login or unlock required, update session env var then retry
-  if [[ -z "${bwItems}" ]]; then
-    sessionKey="$(bw unlock --raw)"
+	local bwItemFormat='.[] | "\(.name) · \(.login.username) \(.id)"'
 
-    if [[ "${sessionKey}" == *"not logged in"* ]]; then
-      sessionKey="$(bw login --raw)"
-    fi
+	# ensure output of `bw list items` (which contains passwords) is sent
+	# directly through jq so that passwords can be stripped out immediately
+	# and not risk exposure later in the script
+	local bwItems="$(
+		export BW_SESSION="${sessionKey}" ;  # set in subshell; avoid external exposure
+		bw list items | jq -r "${bwItemFormat}" 2>/dev/null
+	)"
 
-    export BW_SESSION="${sessionKey}"
+	# if login or unlock required, update session env var then re-fetch items
+	if [[ -z "${bwItems}" ]]; then
+		sessionKey="$( bw unlock --raw )"
 
-    bwfzf "$@"
+		if [[ "${sessionKey}" == *"not logged in"* ]]; then
+			sessionKey="$( bw login --raw )"
+		fi
 
-  else
-    # invoke fzf on items list
-    # use "Here Documents" piping for security, see above
-    bwItem="$(fzf-tmux --nth 1..-2 --with-nth 1..-2 <<EOF
-${bwItems}
-EOF
-)"
-    # get last field (id) from "name username id" row
-    # use "Here Documents" piping for security, see above
-    bwItemId="$(awk '{print $NF}' <<EOF
-${bwItem}
-EOF
-)"
+		# session key has changed; persist the new value
+		if hash bwfzf-session-persistence 2>/dev/null; then
+			if [[ ${argVerbose} == true ]]; then
+				bwfzf-session-persistence action:put "$@" <<-EOF
+					${sessionKey}
+				EOF
+			else
+				(
+					nohup $(  # execute in background...
+						bwfzf-session-persistence action:put "$@" <<-EOF
+							${sessionKey}
+						EOF
+					) &
+				) &>/dev/null  # suppress nohup output
+			fi
+		fi
 
-    echo  # formatting
+		# ensure output of `bw list items` (which contains passwords) is sent
+		# directly through jq so that passwords can be stripped out immediately
+		# and not risk exposure later in the script
+		local bwItems="$(
+			export BW_SESSION="${sessionKey}" ;  # set in subshell; avoid external exposure
+			bw list items | jq -r "${bwItemFormat}" 2>/dev/null
+		)"
 
-    # perform an action (e.g. copy password to clipboard) then ask the user
-    # whether to perform another action or exit
-    while true; do
+		if [[ -z "${bwItems}" ]]; then
+			bwfzf  # retry
+		fi
+	fi
 
-      # 1-9 key - copy username or password in N seconds
-      if [[ "${keyPressed}" =~ ^[0-9]+$ ]]; then
-        lastAction="Copying ${nextField} in ${keyPressed} seconds..."
+	# invoke fzf on items list
+	local bwItem="$(
+		fzf-tmux --nth 1..-2 --with-nth 1..-2 <<-EOF
+			${bwItems}
+		EOF
+	)"
 
-        if [[ "${nextField}" == "username" ]]; then
-          # use "Here Documents" piping for security, see above
-          ( sleep "${keyPressed}" ; $(secure-pbcopy <<EOF
-$(bw get username "${bwItemId}")
-EOF
-) ; echo "Username copied!" ) & disown
-          nextField="password"
-        else
-          # use "Here Documents" piping for security, see above
-          ( sleep "${keyPressed}" ; $(secure-pbcopy <<EOF
-$(bw get password "${bwItemId}")
-EOF
-) ; echo "Password copied!" ) & disown
-          nextField="username"
-        fi
+	# get last field (id) from "name username id" row
+	local bwItemId="$(
+		awk '{print $NF}' <<-EOF
+			${bwItem}
+		EOF
+	)"
 
-      # o key - open uri in browser
-      elif [[ "${keyPressed}" == "o" ]]; then
-        lastAction="URI opened!"
-        open -n "$(bw get uri "${bwItemId}")"
+	echo	# formatting
 
-      # p key - print full entry
-      elif [[ "${keyPressed}" == "p" ]]; then
-        # use "Here Documents" piping for security, see above
-        echo "$(jq 'del(.login.password)' <<EOF
-$(bw get item "${bwItemId}")
-EOF
-)" | jq .
-        echo
+	local keyPressed
+	local lastAction
+	local nextField
 
-      # l key - lock vault & exit
-      elif [[ "${keyPressed}" == "l" ]]; then
-        bw lock
-        break
+	# perform an action (e.g. copy password to clipboard) then ask the user
+	# whether to perform another action or exit
+	while true; do
+		# 1-9 key - copy username or password in N seconds
+		if [[ "${keyPressed}" =~ ^[0-9]+$ ]]; then
+			lastAction="Copying ${nextField} in ${keyPressed} seconds..."
 
-      # enter key - copy password, username, uri, etc.
-      elif [[ -z "${keyPressed}" ]]; then
-        if [[ "${nextField}" == "username" ]]; then
-          # use "Here Documents" piping for security, see above
-          secure-pbcopy <<EOF
-$(bw get username "${bwItemId}")
-EOF
-          lastAction="Username copied!"
-          nextField="password"
-        else
-          # use "Here Documents" piping for security, see above
-          secure-pbcopy <<EOF
-$(bw get password "${bwItemId}")
-EOF
-          lastAction="Password copied!"
-          nextField="username"
-        fi
+			if [[ "${nextField}" == "username" ]]; then
+				(
+					(
+						( sleep "${keyPressed}" ; $(
+							export BW_SESSION="${sessionKey}" ;
+							bw get username "${bwItemId}" | secure-pbcopy
+						) ; echo "Username copied!" >&3 ) & disown
+					) 1>/dev/null  # suppress disown stdout
+				) 3>&1  # redirect file-descriptor 3 through stdout for "copied!" message
+				nextField="password"
+			else
+				(
+					(
+						( sleep "${keyPressed}" ; $(
+							export BW_SESSION="${sessionKey}" ;
+							bw get password "${bwItemId}" | secure-pbcopy
+						) ; echo "Password copied!" >&3 ) & disown
+					) 1>/dev/null  # suppress disown stdout
+				) 3>&1  # redirect file-descriptor 3 through stdout for "copied!" message
+				nextField="username"
+			fi
 
-      # any other key - exit
-      else
-        break
-      fi
+		# o key - open uri in browser
+		elif [[ "${keyPressed}" == "o" ]]; then
+			lastAction="URI opened!"
+			open -n "$( export BW_SESSION="${sessionKey}" ; bw get uri "${bwItemId}" )"
 
-      read -rsn1 -p "${lastAction}
+		# p key - print full entry
+		elif [[ "${keyPressed}" == "p" ]]; then
+			echo "$(
+				export BW_SESSION="${sessionKey}" ;
+				bw get item "${bwItemId}" | jq 'del(.login.password)'
+			)" | jq .
+			echo
+
+		# l key - lock vault & exit
+		elif [[ "${keyPressed}" == "l" ]]; then
+			bw lock
+			break
+
+		# enter key - copy password, username, uri, etc.
+		elif [[ -z "${keyPressed}" ]]; then
+			if [[ "${nextField}" == "username" ]]; then
+				$(
+					export BW_SESSION="${sessionKey}" ;
+					bw get username "${bwItemId}" | secure-pbcopy
+				)
+				lastAction="Username copied!"
+				nextField="password"
+			else
+				$(
+					export BW_SESSION="${sessionKey}" ;
+					bw get password "${bwItemId}" | secure-pbcopy
+				)
+				lastAction="Password copied!"
+				nextField="username"
+			fi
+
+		# any other key - exit
+		else
+			break
+		fi
+
+		read -rsn1 -p "${lastAction}
   enter -> copy ${nextField}
-  0-9   -> copy ${nextField} in N seconds
+  0 - 9 -> copy ${nextField} in N seconds
   o key -> open in browser
   p key -> print full entry (password redacted)
   l key -> lock vault & exit
   other -> exit
 
-"   keyPressed
-    done
-  fi
+"		keyPressed
+	done
 }
diff --git a/bwfzf-gnupg b/bwfzf-gnupg
--- a/bwfzf-gnupg
+++ b/bwfzf-gnupg
@@ -1,315 +1,306 @@
 #!/usr/bin/env bash
 
-bwfzf-gnupg() {
-	# parse args
+bwfzf-session-persistence() {
+	# invoked as
+	# $ bwfzf-session-persistence action:get -v
+	# $ bwfzf-session-persistence action:put -dv
+	# handle arguments accordingly:
+	local argAction="get"
 	local argVerbose=false
 	local argDebug=false
 	bwfzf-argparse "$@"
 	local V="${argVerbose}"  # alias for code readability
 
-	if hash gpg 2>/dev/null; then
-	# use subshell so encrypt/decrypt helper functions are not exposed globally
-	(
+	# ensure gpg is installed
+	if ! hash gpg 2>/dev/null; then
+		echo "Error: You're trying to use `bwfzf-gnupg` but `gpg` is not installed. Try `brew install gnupg` or consult the GnuPG docs for installation instructions on your platform: https://www.gnupg.org/documentation"
+		exit 1
+	fi
 
-		gpgConnect() {
-			local verbose="$1"
-			local outputMode=""
-			[[ "${verbose}" == true ]] && outputMode="-vv"
-			# sed: remove extraneous/non-hex gpg output:
-			# "D 0123456789abcdef OK" -> "0123456789abcdef"
-			gpg-connect-agent ${outputMode} | sed 's/[^a-z0-9]//g'
-		}
+	( # use subshell so encrypt/decrypt helper functions are not exposed globally
 
-		gpgGetSession() {
-			local verbose="$1"
-			gpgConnect "${verbose}" <<-EOF
-				getval bwfzfs
-			EOF
-		}
+	gpgConnect() {
+		local verbose="$1"
+		local outputMode=""
+		[[ "${verbose}" == true ]] && outputMode="-vv"
+		# sed: remove extraneous/non-hex gpg output:
+		# "D 0123456789abcdef OK" -> "0123456789abcdef"
+		gpg-connect-agent ${outputMode} | sed 's/[^a-z0-9]//g'
+	}
 
-		gpgPutSession() {
-			local data=$( cat )
-			local verbose="$1"
-			gpgConnect "${verbose}" <<-EOF
-				putval bwfzfs ${data}
-			EOF
-		}
+	gpgGetSession() {
+		local verbose="$1"
+		gpgConnect "${verbose}" <<-EOF
+			getval bwfzfs
+		EOF
+	}
 
-		gpgGetFilePath() {
-			local verbose="$1"
-			gpgConnect "${verbose}" <<-EOF
-				getval bwfzff
-			EOF
-		}
+	gpgPutSession() {
+		local data=$( cat )
+		local verbose="$1"
+		gpgConnect "${verbose}" <<-EOF
+			putval bwfzfs ${data}
+		EOF
+	}
 
-		gpgPutFilePath() {
-			local data=$( cat )
-			local verbose="$1"
-			gpgConnect "${verbose}" <<-EOF
-				putval bwfzff ${data}
-			EOF
-		}
+	gpgGetFilePath() {
+		local verbose="$1"
+		gpgConnect "${verbose}" <<-EOF
+			getval bwfzff
+		EOF
+	}
 
+	gpgPutFilePath() {
+		local data=$( cat )
+		local verbose="$1"
+		gpgConnect "${verbose}" <<-EOF
+			putval bwfzff ${data}
+		EOF
+	}
+
+	if hash bitagent 2>/dev/null; then
+		# start bitagent if it's not running already
+		bitagent ~/.bwfzfs.sock 2>/dev/null
+	fi
+
+	bitAgentPutSession() {
+		local data=$( cat )
 		if hash bitagent 2>/dev/null; then
-			# start bitagent if it's not running already
-			bitagent ~/.bwfzfs.sock 2>/dev/null
+			nc -U ~/.bwfzfs.sock <<-EOF
+				P${data}
+			EOF
 		fi
+	}
 
-		bitAgentPutSession() {
-			local data=$( cat )
-			if hash bitagent 2>/dev/null; then
-				nc -U ~/.bwfzfs.sock <<-EOF
-					P${data}
-				EOF
-			fi
-		}
+	bitAgentGetSession() {
+		if hash bitagent 2>/dev/null; then
+			nc -U ~/.bwfzfs.sock <<-EOF
+				G
+			EOF
+		fi
+	}
 
-		bitAgentGetSession() {
-			if hash bitagent 2>/dev/null; then
-				nc -U ~/.bwfzfs.sock <<-EOF
-					G
-				EOF
-			fi
-		}
+	encode() {
+		xxd -plain -cols 9999
+	}
 
-		encode() {
-			xxd -plain -cols 9999
-		}
+	decode() {
+		xxd -plain -revert -cols 9999
+	}
 
-		decode() {
-			xxd -plain -revert -cols 9999
-		}
+	wrapArmor() {
+		local data=$( cat )
+		cat <<-EOF
+			-----BEGIN PGP MESSAGE-----
+			${data}
+			-----END PGP MESSAGE-----
+		EOF
+	}
 
-		wrapArmor() {
-			local data=$( cat )
-			cat <<-EOF
-				-----BEGIN PGP MESSAGE-----
+	unwrapArmor() {
+		sed -e 's/-----BEGIN PGP MESSAGE-----//g' -e 's/-----END PGP MESSAGE-----//g'
+	}
+
+	encrypt() {
+		local data=$( cat )
+		local verbose="$1"
+		local outputMode=""
+
+		# generate passphrase for gpg symmetric encryption
+		# https://security.stackexchange.com/questions/113309/is-a-43-character-gpg-symmetric-passphrase-as-secure-as-a-256-bit-key
+		local pass=$( bw generate --length 50 )
+
+		# use "Here Documents" shell feature to pipe session data securely to gpg
+		# this avoids leaking variable contents to pipe or process snooping
+		# <<-EOF used instead of <<< for portability,
+		#        per https://stackoverflow.com/a/21171367/11776945
+		# --symmetric       : passphrase-only encryption, no public/private keypair
+		# --yes             : (over)write output file even if it already exists
+		# --passphrase-fd 3 : send passphrase over file descriptor 3 to avoid echo
+		# --batch           : necessary for --passphrase-fd
+		# --armor           : encrypt to "email-safe" ascii format; more resiliant
+		# --output -        : force gpg to send output over stdout; no write to disk
+		[[ ${verbose} == true ]] && outputMode="-vv"
+		local encryptedData=$(
+			gpg --symmetric --yes --passphrase-fd 3 --batch --armor --output - ${outputMode} <<-EOF 3<<-EOFFD3
 				${data}
-				-----END PGP MESSAGE-----
 			EOF
-		}
+				${pass}
+			EOFFD3
+		)
 
-		unwrapArmor() {
-			sed -e 's/-----BEGIN PGP MESSAGE-----//g' -e 's/-----END PGP MESSAGE-----//g'
-		}
-
-		encrypt() {
-			local data=$( cat )
-			local verbose="$1"
-			local outputMode=""
-
-			# generate passphrase for gpg symmetric encryption
-			# https://security.stackexchange.com/questions/113309/is-a-43-character-gpg-symmetric-passphrase-as-secure-as-a-256-bit-key
-			local pass=$( bw generate --length 50 )
-
-			# use "Here Documents" shell feature to pipe session data securely from $BW_SESSION to gpg
-			# this avoids leaking variable contents to pipe or process snooping
-			# <<-EOF used instead of <<< for portability, per https://stackoverflow.com/a/21171367/11776945
-			# --symmetric       : passphrase-only encryption, no public/private keypair
-			# --yes             : (over)write output file even if it already exists
-			# --passphrase-fd 3 : send passphrase over file descriptor 3 to avoid echoing it into stdin (leaking to process list)
-			# --batch           : necessary for --passphrase-fd
-			# --armor           : encrypt to "email-safe" format that's more resiliant to whitespace alterations
-			# --output -        : force gpg to send output over stdout (piped to perm-secured file)
-			# store the encrypted session key in gpg-agent
-			[[ ${verbose} == true ]] && outputMode="-vv"
-			local encryptedData=$(
-				gpg --symmetric --compress-level 0 --yes --passphrase-fd 3 --batch --armor --output - ${outputMode} <<-EOF2 3<<-EOF3
-					${data}
-				EOF2
-					${pass}
-				EOF3
-			)
-
-			# get the 8-octet hex-encoded salt value used during encryption:
-			local salt="$(
-			  echo | ( gpg --list-packets 2>&1 | grep -o '[0-9A-F]\{16\}' ) <<-EOF
-					${encryptedData}
-				EOF
-			)"
-
-			# hex-encode the passphrase for use with gpg-connect-agent preset_passphrase
-			# tr -d '\n' - need to remove trailing newline from EOF input
-			local hexPass="$(
-				( tr -d '\n' | hexdump -v -e '/1 "%02X"' ) <<-EOF
-					${pass}
-				EOF
-			)"
-
-			# preset the passphrase in gpg-agent
-			# "S" prefix necessary for salt-based cacheid: https://superuser.com/a/1485486/1093343
-			gpgConnect ${verbose} <<-EOF
-				preset_passphrase S${salt} -1 ${hexPass}
-			EOF
-
-			cat <<-EOF
+		# get the 8-octet hex-encoded salt value used during encryption:
+		# echo : force immediate command output in all cases; don't wait for user input
+		local salt="$(
+		  echo | ( gpg --list-packets 2>&1 | grep -o '[0-9A-F]\{16\}' ) <<-EOF
 				${encryptedData}
 			EOF
-		}
+		)"
 
-		decrypt() {
-			local verbose="$1"
-			if [[ "${verbose}" == true ]]; then
-				gpg --decrypt -vv --armor
-			else
-				gpg --decrypt 2>/dev/null
-			fi
-		}
-
-		part() {
-			local data="$( cat )"
-			local nthPart="$1"
-			local numParts="$2"
-			# round up -> (numer+(denom-1))/denom
-			local lenPart=$(( ( ${#data} + ( numParts - 1 ) ) / numParts ))
-			local start=$(( ( lenPart * ( nthPart - 1 ) ) + 1 ))
-			local end=$(( ( start + lenPart ) - 1 ))
-
-			cut "-c${start}-${end}" <<-EOF
-				${data}
+		# hex-encode the passphrase for use with gpg-connect-agent preset_passphrase
+		# tr -d '\n' : need to remove trailing newline from EOF input
+		local hexPass="$(
+			( tr -d '\n' | hexdump -v -e '/1 "%02X"' ) <<-EOF
+				${pass}
 			EOF
-		}
+		)"
 
-		outputDebugInfo() {
-			echo '┌────retrieved-file-path────┐'
-			gpgGetFilePath
-			echo '└───────────────────────────┘'
-			echo '┌─────decoded-file-path─────┐'
-			gpgGetFilePath | decode
-			echo '└───────────────────────────┘'
-			echo '┌────decrypted-file-path────┐'
-			gpgGetFilePath | decode | decrypt
-			echo '└───────────────────────────┘'
+		# preset the passphrase in gpg-agent
+		# "S" prefix necessary for salt-based cacheid: https://superuser.com/a/1485486/1093343
+		gpgConnect ${verbose} <<-EOF
+			preset_passphrase S${salt} -1 ${hexPass}
+		EOF
 
-			local part=1
-			local parts=2
+		cat <<-EOF
+			${encryptedData}
+		EOF
+	}
 
-			if hash bitagent 2>/dev/null; then
-				parts=3
-				echo "┌─retrieved-session-key-${part}/${parts}─┐"
-				bitAgentGetSession
-				echo '└───────────────────────────┘'
-				part=$(( part + 1 ))
-			fi
-
-			echo "┌─retrieved-session-key-${part}/${parts}─┐"
-			cat <$( gpgGetFilePath | decode | decrypt )
-			echo '└───────────────────────────┘'
-
-			part=$(( part + 1 ))
-
-			echo "┌─retrieved-session-key-${part}/${parts}─┐"
-			gpgGetSession
-			echo '└───────────────────────────┘'
-
-			echo '┌─full-decoded-session-key──┐'
-			decode <<-EOF
-				$(
-					cat <$( gpgGetFilePath | decode | decrypt )
-				)$(
-					gpgGetSession
-				)$(
-					bitAgentGetSession
-				)
-			EOF
-			echo '└───────────────────────────┘'
-
-			echo '┌─full-wrapped-session-key──┐'
-			( decode | wrapArmor ) <<-EOF
-				$(
-					cat <$( gpgGetFilePath | decode | decrypt )
-				)$(
-					gpgGetSession
-				)$(
-					bitAgentGetSession
-				)
-			EOF
-			echo '└───────────────────────────┘'
-
-			echo '┌─full-decrypted-session-key┐'
-			( decode | wrapArmor | decrypt ) <<-EOF
-				$(
-					cat <$( gpgGetFilePath | decode | decrypt )
-				)$(
-					gpgGetSession
-				)$(
-					bitAgentGetSession
-				)
-			EOF
-			echo '└───────────────────────────┘'
-		}
-
-		# ensure no user-set GPG_TTY interferes with gpg/pinentry interaction below; restore at end of function
-		local originalGpgTty="${GPG_TTY}"
-		export GPG_TTY=""
-
-		local sessionKey="${BW_SESSION}"
-
-		# set BW_SESSION env var from gpg if necessary
-		if [[ -z "${sessionKey}" ]]; then
-			export BW_SESSION="$(
-				( decode | wrapArmor | decrypt $V ) <<-EOF
-					$(
-						cat <$( gpgGetFilePath $V | decode | decrypt $V )
-					)$(
-						gpgGetSession $V
-					)$(
-						bitAgentGetSession
-					)
-				EOF
-			)"
-
-			[[ ${argDebug} == true ]] && outputDebugInfo
-		fi
-
-		if hash bwfzf-autolock 2>/dev/null; then
-			bwfzf-autolock "$@"
-		elif hash bwfzf 2>/dev/null; then
-			bwfzf "$@"
+	decrypt() {
+		local verbose="$1"
+		if [[ "${verbose}" == true ]]; then
+			gpg --decrypt -vv --armor
 		else
-			echo "Error: You're trying to use `bwfzf-gnupg` but the command `bwfzf` is not available. Add `source /path/to/bwfzf` to your .bashrc and try again."
+			gpg --decrypt 2>/dev/null
+		fi
+	}
+
+	part() {
+		local data="$( cat )"
+		local nthPart="$1"
+		local numParts="$2"
+		# round up -> (numer+(denom-1))/denom
+		local lenPart=$(( ( ${#data} + ( numParts - 1 ) ) / numParts ))
+		local start=$(( ( lenPart * ( nthPart - 1 ) ) + 1 ))
+		local end=$(( ( start + lenPart ) - 1 ))
+
+		cut "-c${start}-${end}" <<-EOF
+			${data}
+		EOF
+	}
+
+	outputDebugInfo() {
+		echo '┌────retrieved-file-path────┐'
+		gpgGetFilePath
+		echo '└───────────────────────────┘'
+		echo '┌─────decoded-file-path─────┐'
+		gpgGetFilePath | decode
+		echo '└───────────────────────────┘'
+		echo '┌────decrypted-file-path────┐'
+		gpgGetFilePath | decode | decrypt
+		echo '└───────────────────────────┘'
+
+		local part=1
+		local parts=2
+
+		if hash bitagent 2>/dev/null; then
+			parts=3
+			echo "┌─retrieved-session-key-${part}/${parts}─┐"
+			bitAgentGetSession
+			echo '└───────────────────────────┘'
+			part=$(( part + 1 ))
 		fi
 
-		# if $BW_SESSION has changed, update session key stored via gpg
-		if [[ ${sessionKey} != ${BW_SESSION} ]]; then
-			sessionKey=${BW_SESSION}
-			local filePath=$( mktemp )  # perms should be 600 / -rw------- (r/w only curr user)
+		echo "┌─retrieved-session-key-${part}/${parts}─┐"
+		cat <$( gpgGetFilePath | decode | decrypt )
+		echo '└───────────────────────────┘'
 
-			( encrypt $V | encode | gpgPutFilePath $V ) <<-EOF
-				${filePath}
-			EOF
+		part=$(( part + 1 ))
 
-			local encryptedSessionKey=$(
-				( encrypt $V | unwrapArmor | encode ) <<-EOF
-					${sessionKey}
-				EOF
+		echo "┌─retrieved-session-key-${part}/${parts}─┐"
+		gpgGetSession
+		echo '└───────────────────────────┘'
+
+		echo '┌─full-decoded-session-key──┐'
+		decode <<-EOF
+			$(
+				cat <$( gpgGetFilePath | decode | decrypt )
+			)$(
+				gpgGetSession
+			)$(
+				bitAgentGetSession
 			)
+		EOF
+		echo '└───────────────────────────┘'
 
-			local numParts=2
+		echo '┌─full-wrapped-session-key──┐'
+		( decode | wrapArmor ) <<-EOF
+			$(
+				<$( gpgGetFilePath | decode | decrypt )
+			)$(
+				gpgGetSession
+			)$(
+				bitAgentGetSession
+			)
+		EOF
+		echo '└───────────────────────────┘'
 
-			# if bitagent is available, store last 3rd of session key there
-			if hash bitagent 2>/dev/null; then
-				numParts=3
-				( part 3 ${numParts} | bitAgentPutSession ) <<-EOF
-					${encryptedSessionKey}
-				EOF
-			fi
+		echo '┌─full-decrypted-session-key┐'
+		( decode | wrapArmor | decrypt ) <<-EOF
+			$(
+				<$( gpgGetFilePath | decode | decrypt )
+			)$(
+				gpgGetSession
+			)$(
+				bitAgentGetSession
+			)
+		EOF
+		echo '└───────────────────────────┘'
+	}
 
-			( part 1 ${numParts} > "${filePath}" ) <<-EOF
+	# ensure no user-set GPG_TTY interferes with gpg/pinentry interaction below; restore at end of function
+	local originalGpgTty="${GPG_TTY}"
+	export GPG_TTY=""
+
+	if [[ "${argAction}" == "get" ]]; then
+		( decode | wrapArmor | decrypt $V ) <<-EOF
+			$(
+				<$( gpgGetFilePath $V | decode | decrypt $V )
+			)$(
+				gpgGetSession $V
+			)$(
+				bitAgentGetSession
+	  	)
+		EOF
+
+	elif [[ "${argAction}" == "put" ]]; then
+		local sessionKey=$( cat )   # take session key from stdin
+		local filePath=$( mktemp )  # perms should be 600 / -rw------- (r/w only curr user)
+
+		( encrypt $V | encode | gpgPutFilePath $V ) <<-EOF
+			${filePath}
+		EOF
+
+		local encryptedSessionKey=$(
+			( encrypt $V | unwrapArmor | encode ) <<-EOF
+				${sessionKey}
+			EOF
+		)
+
+		local numParts=2
+
+		# if bitagent is available, store last 3rd of session key there
+		if hash bitagent 2>/dev/null; then
+			numParts=3
+			( part 3 ${numParts} | bitAgentPutSession ) <<-EOF
 				${encryptedSessionKey}
 			EOF
-
-			( part 2 ${numParts} | gpgPutSession $V ) <<-EOF
-				${encryptedSessionKey}
-			EOF
-
-			[[ ${argDebug} == true ]] && outputDebugInfo
 		fi
 
-		# restore gpg/pinentry env vars
-		export GPG_TTY="${originalGpgTty}"
-	)
-	else
-		echo "Error: You're trying to use `bwfzf-gnupg` but `gpg` is not installed. Try `brew install gnupg` or consult the GnuPG docs for installation instructions on your platform: https://www.gnupg.org/documentation"
+		( part 1 ${numParts} > "${filePath}" ) <<-EOF
+			${encryptedSessionKey}
+		EOF
+
+		( part 2 ${numParts} | gpgPutSession $V ) <<-EOF
+			${encryptedSessionKey}
+		EOF
 	fi
+
+	# output debug info over stderr so as not to interfere with session key output
+	[[ ${argDebug} == true ]] && outputDebugInfo >&2
+
+	# restore gpg/pinentry env vars
+	export GPG_TTY="${originalGpgTty}"
+
+	) # end subshell
 }
diff --git a/bwfzf-osx-keychain b/bwfzf-osx-keychain
--- a/bwfzf-osx-keychain
+++ b/bwfzf-osx-keychain
@@ -1,33 +1,33 @@
 #!/usr/bin/env bash
 
-bwfzf-osx-keychain() {
-  if hash security 2>/dev/null; then
-    local sessionKey="${BW_SESSION}"
+bwfzf-session-persistence() {
+	# invoked as
+	# $ bwfzf-session-persistence action:get -v
+	# $ bwfzf-session-persistence action:put -dv
+	# handle arguments accordingly:
+	local argAction="get"
+	local argVerbose=false
+	local argDebug=false
+	bwfzf-argparse "$@"
 
-    # set BW_SESSION env var from keychain if necessary
-    if [[ -z "${sessionKey}" ]]; then
-      sessionKey="$(security find-generic-password -a "${USER}" -s bw -w 2> /dev/null)"
-      export BW_SESSION="${sessionKey}"
-    fi
+  if ! hash security 2>/dev/null; then
+    echo "Error: You're trying to use `bwfzf-osx-keychain` but the keychain cli command `security` does not exist. Are you sure this is OSX?" >&2
+		exit 1
+	fi
 
-    if hash bwfzf-autolock 2>/dev/null; then
-      bwfzf-autolock
-    elif hash bwfzf 2>/dev/null; then
-      bwfzf
-    else
-      echo "Error: You're trying to use `bwfzf-gnupg` but the command `bwfzf` is not available. Add `source /path/to/bwfzf` to your .bashrc and try again."
-    fi
+	local outputMode="-q"
+	if [[ "${argVerbose}" == true ]]; then
+		outputMode="-v"
+	fi
 
-    # if $BW_SESSION has changed, update session key stored via keychain
-    if [[ "${sessionKey}" != "${BW_SESSION}" ]]; then
-      # -U : update if already exists
-      # -T : revoke access for all applications (set blank "")
-      # EOF: supply BW_SESSION data over stdin so it's not exposed in process list
-      security -i <<EOF
-add-generic-password -a "${USER}" -s bw -U -T "" -w "${BW_SESSION}"
-EOF
-    fi
-  else
-    echo "Error: You're trying to use `bwfzf-osx-keychain` but the keychain cli command `security` does not exist. Are you sure this is OSX?"
-  fi
+	if [[ "${argAction}" == "get" ]]; then
+		security -i "${outputMode}" 2>/dev/null <<-EOF
+			find-generic-password -a "${USER}" -s bw -w
+		EOF
+	elif [[ "${argAction}" == "put" ]]; then
+		local sessionKey=$( cat )   # take session key from stdin
+		security -i "${outputMode}" 2>/dev/null <<-EOF
+			add-generic-password -a "${USER}" -s bw -U -T "" -w "${sessionKey}"
+		EOF
+	fi
 }
